chore: setup some common config (#66)
* chore: setup some common config

* chore: setup some common config

* chore: setup commit lint

diff --git a/common/git-hooks/commit-msg b/common/git-hooks/commit-msg
--- a/common/git-hooks/commit-msg
+++ b/common/git-hooks/commit-msg
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # This is an example Git hook for use with Rush.  To enable this hook, rename this file
 # to "commit-msg" and then run "rush install", which will copy it from common/git-hooks
@@ -18,8 +18,22 @@
 
 # This example enforces that commit message should contain a minimum amount of
 # description text.
-if [ `cat $1 | wc -w` -lt 3 ]; then
-  echo ""
-  echo "Invalid commit message: The message must contain at least 3 words."
-	exit 1
+# if [ `cat $1 | wc -w` -lt 3 ]; then
+#   echo ""
+#   echo "Invalid commit message: The message must contain at least 3 words."
+#   exit 1
+# fi
+
+# rebase 过程中分支名格式为 (no branch, rebasing chore/replace-rushtool)
+# 正常提交时分支名格式为 chore/replace-rushtool
+BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
+# 如果匹配到 rebase 格式的输出，认为是在rebase ，则跳过自动推送
+if [[ "X${BRANCH_NAME}" == "X(no branch"* ]]; then
+  exit
+else
+  node common/scripts/install-run-rush.js -q commitlint \
+    --config common/autoinstallers/rush-commitlint/commitlint.config.js \
+    --edit "$1" || exit 1
+  # 如果当前分支是 main 分支，则不进行推送
+  node infra/rush-x/bin/run change || exit 1
 fi
